:PROPERTIES:
:ID:       B92D3F76-BAC9-4EF3-A81F-91C6F605EF59
:END:
#+TITLE: Letters To Me

Migrating https://letters.codeklutz.com/ to this braindump to make myself easier to fetch and process.









- Web extension that converts video audio to text and stores it in file

27 February,2022, Tuesday @4:40pm

Since these days I’m learning thru other course videos such as Coursera ,udemy and usually I have notes (thru note.codeklutz.com) but then an idea of actually converting any video’s audio into text came up.

But as to how to detect every video’s audio seems a challenge for now.
Web extension which screen records and turns it into a gif .

15 February,2022, Tuesday @5:00pm

I came across a situation at work today where I had to explain a problem having on a site witb many redirections happening.Now I thought I could have avoided one meeting if I could just send a small gif or video but I felt lazy to even start the screen recorder on Mac.

Hence the idea of having a web extension which quickly records and Makes into a gif arose.

- Using google sheets as a database???

12 February,2022, Saturday @4:30am

I get the wackiest ideas at night but as I have been working on a small side project which is using MySQL db .I realised how much cost and pain it’s gonna cost me to host it.

And then my mind wandered as to what alternative I can use as a database? I thought of two things:- Firebase as a primary database and second one which sounds weird at first is google sheets.

Google sheets is free and it has an API for small projects maybe I can use it as a db .Just maybe it might work.
- Which approach for my minimal note taking tool?

11 February,2022,Friday @12:28pm

I have been curious about how slack effortlessly and instantly manages to sync messages between desktop and mobile apps.The experience is beautiful.Made me wonder how they actually do it.My friend simply said push notifications which made me read about it,not sure if I understand the push notifications completely but I did ccome come across background sync which does offline syncing between mobile and web app.. Which made me wonder which approach I should take for my minimal browser based note taking tool?

Should I just store the messages on user’s local storage? But that would mean I can’t sync it between multiple browsers such as between my mobile browser and web browser and that would not be convenient.

Should I keep the note taking account based and fetch from db? Seems like my typical approach.

OR should I keep the note taking link based like how paste bin gives you specific link and when you click on it you get contents from that specific link?

OR should I keep it session based? But then I will have to keep the session alive for ever doesn’t seem like a good approach.

- SMS messages or push notifications to myself.

7 February ,2022,Monday @11:45 am

These days I pay attention more to my sms messages than any other app(the shopaholic in me wants to go track the order). But then the idea of sending sms messages to myself to do basic exercise and chores at specific times struck me.

I could use something like go to send sms or if sms implementation becomes a pain there are always push notifications.Could use rest protocol to send sms.Need to research this more. I could use some sort of web app which configures what text and sms to send based on specific times , configure to send the SMS at that time.

- Explaining Why this Tech or study notes on practice repo readme pages.

7 February ,2022,Monday @2:09 am

Today I went thru one of my senior Dev’s GitHub profile (guilty as charged).And I found a interesting and useful habit. The senior dev wrote his study notes on read me and also the reasons and usecases as to why this tech is useful and could be used.

Normally when I study use cases I forget about other use cases and tend to remember hardly one or two prominent ones. Plus this could a useful while I need to revise particular concepts and I have them handy on my GitHub.

I could even explain it here but it might get too verbose so I would only explain which fascinated me to use that tech for some application.

But in general even I should start posting my notes on practice repos readme.

- Need to decide on a minimalist ui or framework for small quick projects.

6 February,2022 ,Sunday @4:12am

I love this minimal ui of Jekyll where I write here and would actually love something similar to implement as a quick to go ii for my personal projects. I found this framework called Pico which is close to this ui but integration of buttons and other elements seems to be a a bit of challenge. Another potential framework could be neat.css .this one seems simpler since it has two files and open to manipulation.Lets see which One I decide. On.
Using browser based tool for creating notes?Instead of spacemacs

6 February,2022,Sunday @4:08am

I have been using spacemacs as my note taking tool these days .It does the job really well and the presentation is sophisticated too.But since I have been using it only as a note taking tool.and nothing else like editor or magit.I have to keep context switching to another app . Plus exporting org to pdf has been a challenge especially tables.

Would prefer if this note taking system was browser based so if I had one less app to switch to. With a minimalist UI.

- Browser app or command line to write to it to here

5 February,2022, Saturday @ 2:04pm

I was thinking about using GitHub mobile app to edit to this file here instead of using the mobile browser all the time. But found out I can’t edit files on the mobile app.Now that’s a shame.

So the idea to write some small command line utility or browser app which writes to this file or some kind PWA which writes to this file would be good.

I could use GitHub itself rather than creating a command line tool since this file resides on GitHub and is hosted thru Jekyll.

But rather create a small page which takes input and writes to this file in this repo.Since I tend to edit from mobile a lot ,app seems like a good idea.

For command line tool I will still need GitHub login creds to write to this which sort of defeats the purpose of not using GitHub.

- Audio blog feature on my blog.

5 February, 2022, Friday @ 4:50am

Need to add speech to text feature on my blog. I found a old software which gives me decent audio on UK accent but need to copy paste the text ,generate audio and add the same in the local and push it.I need to find a way to automate this.

PowerAutomate desktop in windows seems like a good option but isn’t free for normies ,only students and professionals.Could also dabble within desktop testing tools.

- FAT-Find Among Tabs web extension.

5 February, 2022, Friday @ 4:29am

Most of the times at work during hunting among a lot of confluence docs tabs I tend to get a little lost in navigating back to the tab in which I wanted to go .

So a cross browser extension which finds text among all tabs and highlight that particular tab so navigation could be easier.

I was thinking of chrome extension before but since I switched to mozilla,cross browser extension would be ideal.

It could have a simple UI taking some input but that input keyword needs to be searched across all tabs within a window (different windows not sure if it’s possible yet) and highlight maybe the top tab part.Also searching the tab within the tab titles.

- Unpolished scrambling thoughts

4 February,2022 @10pm

Even though I do have a blog where I do write occasionally , sometimes thoughts aren’t just polished or good enough to be on the blog or are not at that readystage yet.

So I have decided to write here my scrambling little tech ideas or thoughts which I can later build a blog or project on.

Something I can read back on to get some ideas when I’m not feeling creative enough.
